### ISSUE TITLE
有bug

### ISSUE THREAD

**Issue by dazhuangge** [mnixry/Tieba2MD#2]
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
=========== RESTART: C:\Users\guoce\Downloads\Tieba2MD-2.0\Main.py ===========
Traceback (most recent call last):
  File "C:\Users\guoce\Downloads\Tieba2MD-2.0\Main.py", line 10, in <module>
    from Markdown import markdown
  File "C:\Users\guoce\Downloads\Tieba2MD-2.0\Markdown.py", line 14, in <module>
    from Image import image
  File "C:\Users\guoce\Downloads\Tieba2MD-2.0\Image\__init__.py", line 16, in <module>
    from .fileUpload import MultiPartForm
  File "C:\Users\guoce\Downloads\Tieba2MD-2.0\Image\fileUpload.py", line 18, in <module>
    from avalon_framework import Avalon
  File "C:\Users\guoce\Downloads\Tieba2MD-2.0\avalon_framework\__init__.py", line 23, in <module>
    from colorama import init
ModuleNotFoundError: No module named 'colorama'
>>>

**Comment by mnixry** [comment]
<del>这个项目其实都摸了很久的说</del>
这个程序很久没维护了，这段时间有空我会考虑重构一下

**Comment by mnixry** [comment]
另外如果你下的是release里面的话可以试试先`pip`安装`colorama`
因为年久失修我也不太清楚还能不能用（逃

**Comment by dazhuangge** [comment]
好了，牛B

**Comment by dazhuangge** [comment]
> 另外如果你下的是释放里面的话可以试试先`pip`安装`colorama`
> 因为年久失修我也不太清楚还能不能用（逃

厉害厉害

**Comment by dazhuangge** [comment]
<img width="322" alt="20191225123323" src="https://user-images.githubusercontent.com/33365892/71432220-d1255200-2712-11ea-8bb1-01972cc9b8de.png">
感觉文字有些乱，是不是还有什么问题

**Comment by dazhuangge** [comment]
> <img alt="20191225123323" width="322" src="https://user-images.githubusercontent.com/33365892/71432220-d1255200-2712-11ea-8bb1-01972cc9b8de.png">
> 
> 感觉文字有些乱，是不是还有什么问题

但是用命令行的话是好的

**Comment by mnixry** [comment]
颜色代码貌似还有点问题
不知道colorama什么时候不是标准库的
顺便问一下输出的markdown文件有没有问题（

**Comment by dazhuangge** [comment]
> 颜色代码貌似还有点问题
> 不知道colorama什么时候不是标准库的
> 顺便问一下输出的markdown文件有没有问题（

大概浏览了一下，没用问题，图片也正常
<img width="734" alt="20191225182937" src="https://user-images.githubusercontent.com/33365892/71443197-99370280-2744-11ea-9c6f-27bc8ed65d69.png">
命令行是好的，python自带的idle才会出现上述问题

**Comment by dazhuangge** [comment]
> 颜色代码貌似还有点问题
> 不知道colorama什么时候不是标准库的
> 顺便问一下输出的markdown文件有没有问题（

另外问一下，这个图片是贴吧的原图片吗，

**Comment by mnixry** [comment]
> 
> 
> > 颜色代码貌似还有点问题
> > 不知道colorama什么时候不是标准库的
> > 顺便问一下输出的markdown文件有没有问题（
> 
> 大概浏览了一下，没用问题，图片也正常
> <img alt="20191225182937" width="734" src="https://user-images.githubusercontent.com/33365892/71443197-99370280-2744-11ea-9c6f-27bc8ed65d69.png">
> 命令行是好的，python自带的idle才会出现上述问题

那就是idle没有ASCII控制字符支持
这个不属于程序问题（光速逃）

另外关于图片的问题的话应该和你下载的版本有关
看一下markdown文件里面的图片链接，我估计是百度原链的可能性比较大
这段时间在开新分支重置程序了，可能一月中旬能出个新Release
